### PR TITLE
Xperia 10 II

### PR DESCRIPTION
**Pull request by sledges**
`dhd: remove ganges (Xperia 10) and add seine (Xperia 10 II)` needs mer-hybris/droid-system-device#16 and its submodule update.

### CODE REVIEW

**Comment by Thaodan** [comment]
Please update/fix the commit ref of the submodule hybris-boot

**Comment by sledges** [comment]
> Please update/fix the commit ref of the submodule hybris-boot

This is still WIP, and there might be other changes to submodules as we go ahead with testing, I'll update submodules before merging (this applies to all open PRs).

**Comment by Thaodan** [comment]
You removed droid-system-vendor but still depend on it.

**Comment by sledges** [comment]
> You removed droid-system-vendor but still depend on it.

Thanks fixed.

**Review by mkosola — APPROVED** [review]

**Pull request merged**
